GET http://localhost:3000/articles

###

GET http://localhost:3000/articles/5f296c6ea897aba81c9880db

###

POST http://localhost:3000/articles
Content-type: application/json

{
    "title": "pixel 5 !",
    "author": "Ricky Rojas",
    "source": "android central",
    "comments": 10
}

###

GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-type: application/json

{
    "userName": "Ricky",
    "password": "password"
}

###
GET http://localhost:3000/users/5f29a962122e1cf475b0ffdc

###

GET http://localhost:3000/sites

###
POST http://localhost:3000/sites
Content-type: application/json

{
    "name": "www.androidcentral.com"
}

###
GET http://localhost:3000/sites/1