GET http://localhost:3000/articles

###

GET http://localhost:3000/articles/5f296c6ea897aba81c9880db

###

POST http://localhost:3000/articles
Content-type: application/json

{
    "title": "pixel 5 !",
    "author": "Ricky Rojas",
    "comments": 10,
    "source": "5f2df0addcaee41c01c725f9"
}

###

GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-type: application/json

{
    "userName": "new user",
    "password": "password2"
}

###
GET http://localhost:3000/users/5f29a962122e1cf475b0ffdc

###

GET http://localhost:3000/sites

###
POST http://localhost:3000/sites
Content-type: application/json

{
    "name": "New Site",
    "url": "www.newsite.com"
}

### -- sites/:id/articles not working!!!!!!!!
GET http://localhost:3000/sites/5f2df0addcaee41c01c725f9/articles
